name: color_app
description: A new Flutter project.

publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.4.0
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  lottie: ^2.0.0
  confetti: ^0.7.0
  bitsdojo_window: ^0.1.4
  media_kit: ^1.1.10                             
  media_kit_video: ^1.2.4                        
  media_kit_libs_video: ^1.0.4 

  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  


flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/images/coloring/
   - assets/images/dialog/
   - assets/images/matching_colors/
   - assets/images/coloring/coloring_page_1/
   - assets/images/coloring/coloring_page_2/
   - assets/images/coloring/coloring_page_3/
   - assets/images/coloring/coloring_page_4/
   - assets/images/coloring/coloring_page_5/
   - assets/images/coloring/coloring_page_6/
   - assets/images/coloring/coloring_page_7/
   - assets/images/coloring/coloring_page_8/
   - assets/images/coloring/coloring_page_9/
   - assets/images/coloring/coloring_page_10/
   - assets/images/coloring/coloring_page_11/
   - assets/images/coloring/coloring_page_12/
   - assets/images/coloring/coloring_page_13/
   - assets/images/matching_colors/matching_colors_page_1/
   - assets/images/matching_colors/matching_colors_page_2/
   - assets/images/matching_colors/matching_colors_page_3/
   - assets/images/matching_colors/matching_colors_page_4/
   - assets/images/matching_colors/matching_colors_page_5/
   - assets/images/matching_colors/matching_colors_page_6/
   - assets/images/matching_colors/matching_colors_page_7/
   - assets/images/matching_colors/matching_colors_page_8/
   - assets/images/matching_colors/matching_colors_page_9/
   - assets/images/matching_colors/matching_colors_page_10/
   - assets/images/matching_colors/matching_colors_page_11/
   - assets/images/coloring/brown_false.png
   - assets/images/learning_colors/


   

    
    
    
  

 
